name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup java SDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Build with Maven
        run: mvn clean install

      - name: Unit tests
        run: mvn test
